### ISSUE TITLE
Remove html-minifier

### ISSUE THREAD

**Issue by fengzilong** [regularjs/regular-loader#3]
when meet `<Input value="foo"></Input>` , html-minifier will convert this into `<Input value=foo>`( `caseSensitive` has been set to `true` )
As a result, `Regular.parse` throws an error because there is no close tag found for `Input`

Actually, minifying template string before precompile is meaningless, bundle size doesn't decrease as expected

**Comment by linjinying** [comment]
@fengzilong  你好，我尝试引入`html-minifier`可以帮我解决一个问题，就是处理掉编译之后的换行的空文本节点。或者不引入这个有什么好的方式解决吗？

**Comment by fengzilong** [comment]
@linjinying 我加一个 `preserveWhitespace` 的配置

**Comment by linjinying** [comment]
@fengzilong 请问这个配置支持了吗？麻烦有空维护一下，谢谢
